import './style.css';
import { C, readSettings } from './config';
import { Game } from './game';
import { CourtRenderer } from './renderer';
import { CameraManager } from './camera';
import { CalibrationManager, MotionInterpreter, neutralMotion, poseQuality, type Pose } from './motion';
import { AudioManager } from './audio';
import { DebugInput, syntheticPose } from './synthetic';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const settings=readSettings(),game=new Game(settings),camera=new CameraManager(),interpreter=new MotionInterpreter(),audio=new AudioManager(),debug=new DebugInput();
let screen='home',mode:'camera'|'keyboard'|'synthetic'='camera',calibration:CalibrationManager|null=null,calibrated=false,lastPose:Pose|null=null,lastGood=0,previousPoseTime=0,lastFrame=performance.now(),accumulator=0,fps=60,trackingPaused=false,recovery=0,toastUntil=0,syntheticTime=0;
$('#app').innerHTML=`
<div id="court"></div><div class="vignette"></div>
<header><a class="brand" href="#" aria-label="Motion Badminton home"><span class="brand-icon">↗</span> MOTION<span class="brand-light">BADMINTON</span></a><div class="header-right"><span class="local"><i></i> LOCAL PLAY · PRIVATE BY DESIGN</span><button class="icon" id="settings-open" aria-label="Settings">⚙</button></div></header>
<main id="home" class="panel screen"><div class="eyebrow">STEP INTO THE GAME / 01</div><h1>Your body.<br>Your <em>game.</em></h1><p class="intro">Turn your room into a badminton court.<br>Move, swing, and feel every rally.<br>All you need is your webcam.</p><button class="primary" id="play">PLAY WITH CAMERA <span>↗</span></button><div class="home-actions"><button id="calibrate">Calibrate</button><button id="home-settings">Settings</button><button id="quit">Quit</button></div><div class="safety">↔ &nbsp; Make sure you have clear space around you before playing.<small>Stay approximately in place. No jumping required.</small></div><button id="keyboard" class="text-button">No camera? Open keyboard test →</button><div class="feature-row"><span>01 <b>CONNECT</b></span><span>02 <b>CALIBRATE</b></span><span>03 <b>RALLY</b></span></div></main>
<div id="home-caption"><span>THE COURT IS YOURS</span><b>Less equipment.<br>More instinct.</b><small>WEBCAM CONTROLLED / SINGLES / LOCAL PROTOTYPE</small></div>
<section id="calibration" class="screen hidden dialog"><div class="eyebrow">FIND YOUR FORM</div><h2>Let’s get you ready.</h2><p id="calibration-message">Connecting your camera…</p><div class="progress"><i id="calibration-progress"></i></div><div class="steps"><span>Position</span><span>Racket hand</span><span>Movement</span><span>Reach</span></div><p class="muted">Face the camera with your upper body visible.<br>Keep your movements small and comfortable.</p><button id="calibration-cancel" class="secondary">Back to home</button></section>
<div id="hud" class="screen hidden"><div class="scoreboard"><div><span>YOU</span><b id="your-score">00</b></div><i>:</i><div><span>OPPONENT</span><b id="ai-score">00</b></div><small>RALLY SCORING · FIRST TO 21</small></div><div class="session-label"><i></i><span id="control-label">CAMERA CONTROL</span><span id="tracking-status">TRACKING</span></div><button class="secondary" id="pause">Ⅱ &nbsp; Pause</button><div id="rally-hint"><span id="shot-label">READY</span><b id="instruction">Swing gently upward to serve</b><small id="rally-count">RALLY 0</small></div><div id="keyboard-help" class="hidden">A / D move · W / S reach · SPACE swing · 1 clear / 2 drive / 3 drop / 4 smash / 5 lift</div></div>
<section id="pause-screen" class="screen hidden dialog"><div class="eyebrow">TAKE A BREATHER</div><h2>Match paused.</h2><p>Your next rally is waiting.</p><button id="resume" class="primary">BACK TO COURT ↗</button><button id="recalibrate" class="secondary">Recalibrate camera</button><button id="restart" class="secondary">Restart match</button><button id="back-home" class="text-button">Return home</button></section>
<section id="results" class="screen hidden dialog"><div class="eyebrow">THAT’S A MATCH</div><h2 id="result-title">Well played.</h2><div id="result-score" class="result-score"></div><p id="result-stats"></p><button id="play-again" class="primary">PLAY AGAIN ↗</button><button id="results-home" class="secondary">Home</button></section>
<section id="settings" class="screen hidden dialog"><div class="eyebrow">MAKE IT YOUR GAME</div><h2>Settings</h2><div class="setting-grid"><label>Camera<select id="camera-select"><option value="">Default camera</option></select></label><label>Opponent<select id="difficulty"><option value="easy">Easy</option><option value="normal">Normal</option></select></label><label>Motion assistance<select id="assist"><option value="beginner">Beginner</option><option value="normal">Normal</option></select></label><label>Swing sensitivity<input id="sensitivity" type="range" min="0.6" max="1.8" step="0.1"></label><label>Movement sensitivity<input id="movement" type="range" min="0.5" max="1.8" step="0.1"></label><label>Audio volume<input id="volume" type="range" min="0" max="1" step="0.05"></label><label class="check"><input id="preview" type="checkbox"> Webcam preview</label><label class="check"><input id="debug" type="checkbox"> Developer overlay</label></div><p class="muted">Racket hand: <span id="hand-label">not calibrated</span>. Recalibrate to change hands.<br>Changing camera requires recalibration.</p><button id="settings-done" class="primary">SAVE SETTINGS</button><button id="synthetic" class="text-button">Run synthetic pose diagnostic →</button></section>
<aside id="preview-box" class="hidden"><canvas id="skeleton" width="640" height="480"></canvas><span id="preview-label">LIVE · ON DEVICE</span></aside><pre id="debug-overlay" class="hidden"></pre><div id="tracking-warning" class="hidden">Step back into frame<small>The rally is paused until tracking is stable.</small></div><div id="toast" role="status" class="hidden"></div><div id="error" role="alert" class="hidden"><b>Let’s fix that.</b><p id="error-message"></p><button id="error-close" class="secondary">Got it</button></div><footer><span>MOVE NATURALLY. PLAY FREELY.</span><span>MOTION LAB / PROTOTYPE 0.1</span></footer>`;
let renderer:CourtRenderer;
try{renderer=new CourtRenderer($('#court'));}catch{showError('WebGL could not start. Enable hardware acceleration and open this page in Chrome or Edge.');throw new Error('WebGL unavailable');}
$('#preview-box').prepend(camera.video);
function showError(message:string){$('#error-message').textContent=message;$('#error').classList.remove('hidden');}
function setScreen(next:string){screen=next;document.querySelectorAll('.screen').forEach(e=>e.classList.add('hidden'));$(`#${next==='game'?'hud':next}`).classList.remove('hidden');$('#home-caption').classList.toggle('hidden',next!=='home');$('#tracking-warning').classList.add('hidden');debug.keys.clear();accumulator=0;}
function home(){camera.stop();calibrated=false;lastGood=0;lastPose=null;trackingPaused=false;setScreen('home');}
function startGame(){game.reset();trackingPaused=false;recovery=0;setScreen('game');$('#control-label').textContent=mode==='camera'?'CAMERA CONTROL':mode==='keyboard'?'KEYBOARD TEST':'SYNTHETIC POSE DIAGNOSTIC';$('#keyboard-help').classList.toggle('hidden',mode!=='keyboard');}
async function startCamera(){audio.unlock();audio.volume=settings.volume;mode='camera';calibrated=false;calibration=new CalibrationManager();interpreter.reset();lastPose=null;lastGood=0;previousPoseTime=0;setScreen('calibration');$('#calibration-message').textContent='Connecting camera and loading local pose model…';try{await camera.start(settings.camera);void populateCameras();}catch(e){home();showError((e as Error).message);}}
camera.onError=message=>{if(screen==='game')setScreen('pause-screen');showError(message);};
camera.onPose=(pose,time)=>{lastPose=pose;if(pose&&poseQuality(pose)>=C.confidence){lastGood=performance.now();if(screen==='calibration'&&calibration){const result=calibration.update(pose,Math.min((time-previousPoseTime)/1000,0.1));$('#calibration-message').textContent=result.message;$('#calibration-progress').style.width=`${calibration.progress*100}%`;if(result.done){interpreter.calibration=result.done;interpreter.reset();calibrated=true;$('#hand-label').textContent=result.done.hand;startGame();}}else if(calibrated&&screen==='game'){const m=interpreter.update(pose,time,settings.sensitivity,settings.movement);if(m)game.setMotion(m);}}else {interpreter.reset();if(screen==='calibration'){$('#calibration-message').textContent='Step into frame. Keep shoulders, wrists and hips visible.';calibration?.update(undefined,0);}}previousPoseTime=time;};
async function populateCameras(){try{const devices=await camera.devices();const select=$<HTMLSelectElement>('#camera-select');select.replaceChildren(new Option('Default camera',''),...devices.map((d,i)=>new Option(d.label||`Camera ${i+1}`,d.deviceId)));select.value=settings.camera;}catch{/* Permission-dependent enumeration can be unavailable before camera access. */}}
let settingsReturn='home';
function openSettings(){settingsReturn=screen==='game'?'pause-screen':screen;setScreen('settings');for(const key of ['difficulty','assist','sensitivity','movement','volume'] as const)$<HTMLInputElement>(`#${key}`).value=String(settings[key]);for(const key of ['preview','debug'] as const)$<HTMLInputElement>(`#${key}`).checked=settings[key];void populateCameras();}
$('#settings-done').onclick=()=>{const changed=$<HTMLSelectElement>('#camera-select').value!==settings.camera;settings.camera=$<HTMLSelectElement>('#camera-select').value;settings.difficulty=$<HTMLSelectElement>('#difficulty').value as typeof settings.difficulty;settings.assist=$<HTMLSelectElement>('#assist').value as typeof settings.assist;for(const key of ['sensitivity','movement','volume'] as const)settings[key]=Number($<HTMLInputElement>(`#${key}`).value);for(const key of ['preview','debug'] as const)settings[key]=$<HTMLInputElement>(`#${key}`).checked;try{localStorage.setItem('motion-settings',JSON.stringify(settings));}catch{showError('Settings could not be saved in this browser; they still apply for this session.');}audio.volume=settings.volume;if(changed&&mode==='camera'&&camera.running)void startCamera();else setScreen(settingsReturn==='settings'?'home':settingsReturn);};
$('#play').onclick=()=>void startCamera();$('#calibrate').onclick=()=>void startCamera();$('#recalibrate').onclick=()=>void startCamera();$('#home-settings').onclick=openSettings;$('#settings-open').onclick=openSettings;
$('#keyboard').onclick=()=>{camera.stop();mode='keyboard';audio.unlock();audio.volume=settings.volume;startGame();};
$('#synthetic').onclick=()=>{camera.stop();mode='synthetic';interpreter.reset();interpreter.calibration={center:{x:0.5,y:0.5,z:0},width:0.22,hand:'right',range:0.15,reach:1.8};syntheticTime=0;settings.debug=true;startGame();};
$('#pause').onclick=()=>setScreen('pause-screen');$('#resume').onclick=()=>{interpreter.reset();setScreen('game');};$('#restart').onclick=startGame;$('#play-again').onclick=startGame;
for(const id of ['back-home','results-home','calibration-cancel'])$(`#${id}`).onclick=home;
$('.brand').onclick=e=>{e.preventDefault();home();};$('#quit').onclick=()=>{home();toast('Camera released. You can safely close this tab.');};$('#error-close').onclick=()=>$('#error').classList.add('hidden');
function toast(message:string){$('#toast').textContent=message;$('#toast').classList.remove('hidden');toastUntil=performance.now()+2200;}
window.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select'))return;if(e.code==='Escape'){if(screen==='game')setScreen('pause-screen');else if(screen==='pause-screen')setScreen('game');}if(e.code==='F3'){e.preventDefault();settings.debug=!settings.debug;}if(mode==='keyboard'&&screen==='game'){debug.keys.add(e.key);if(e.code==='Space'){e.preventDefault();if(!e.repeat){debug.swing(performance.now());audio.play('swing');}}const intents=['clear','drive','drop','smash','lift'] as const;if(Number(e.key)>=1&&Number(e.key)<=5)debug.intent=intents[Number(e.key)-1];}});
window.addEventListener('keyup',e=>debug.keys.delete(e.key));window.addEventListener('blur',()=>{debug.keys.clear();if(screen==='game')setScreen('pause-screen');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='game')setScreen('pause-screen');});window.addEventListener('beforeunload',()=>camera.stop());
const skeleton=$<HTMLCanvasElement>('#skeleton'),ctx=skeleton.getContext('2d')!;const edges=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];
function drawPose(){ctx.clearRect(0,0,640,480);if(!lastPose)return;ctx.strokeStyle='#ceff8d';ctx.lineWidth=3;for(const [a,b]of edges){if((lastPose[a].visibility??0)<0.5||(lastPose[b].visibility??0)<0.5)continue;ctx.beginPath();ctx.moveTo(lastPose[a].x*640,lastPose[a].y*480);ctx.lineTo(lastPose[b].x*640,lastPose[b].y*480);ctx.stroke();}for(const p of lastPose){if((p.visibility??0)<0.5)continue;ctx.fillStyle='#f5ffe7';ctx.beginPath();ctx.arc(p.x*640,p.y*480,4,0,Math.PI*2);ctx.fill();}}
let uiClock=0;
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min((now-lastFrame)/1000,0.05);lastFrame=now;fps=fps*0.95+(1/Math.max(dt,0.001))*0.05;
  if(screen==='game'){
    if(mode==='keyboard')game.setMotion(debug.update(now,dt));
    else if(mode==='synthetic'){syntheticTime+=dt;const phase=syntheticTime%1.6;const x=phase<0.3?0.32-phase*1.0:0.20;lastPose=syntheticPose(x,phase<0.3?0.63-phase*1.1:0.30,Math.sin(syntheticTime*0.5)*0.08);const m=interpreter.update(lastPose,now);if(m)game.setMotion(m);}
    if(mode==='camera'){
      const age=now-lastGood;
      if(age>C.staleMs)game.setMotion({...game.motion,swing:false,confidence:0});
      if(age>C.pauseMs){trackingPaused=true;recovery=0;}
      if(trackingPaused&&age<150){recovery+=dt;if(recovery>0.65){trackingPaused=false;interpreter.reset();}}
      $('#tracking-warning').classList.toggle('hidden',!trackingPaused);
    }
    if(!trackingPaused){accumulator+=dt;while(accumulator>=C.dt){game.step(C.dt);accumulator-=C.dt;}}
    for(const event of game.events){audio.play(event.type);if(event.position)renderer.impact(event.position,event.speed);if(event.type==='point')toast(event.text);else if(event.speed)toast(`${event.text} · ${Math.round(event.speed)} km/h`);}game.events=[];
    if(game.state==='over'){$('#result-title').textContent=game.match.winner===0?'You took the court.':'A rally worth replaying.';$('#result-score').textContent=game.match.score.join(' : ');$('#result-stats').textContent=`Best rally: ${game.bestRally} shots · ${game.totalHits} total contacts`;setScreen('results');}
  }
  renderer.render(game,dt);uiClock+=dt;
  if(uiClock>0.1){uiClock=0;$('#your-score').textContent=String(game.match.score[0]).padStart(2,'0');$('#ai-score').textContent=String(game.match.score[1]).padStart(2,'0');$('#shot-label').textContent=game.lastShot;$('#rally-count').textContent=`RALLY ${game.hits}`;$('#instruction').textContent=game.state==='ready'?(game.match.server===0?(mode==='keyboard'?'Press SPACE to serve':'Swing gently upward to serve'):'Opponent preparing to serve'):game.state==='point'?'Reset your stance. Next rally coming.':game.shuttle.lastHit===1?'Meet the shuttle. Swing through.':'Find your position. Stay ready.';$('#tracking-status').textContent=mode!=='camera'?'TEST INPUT':trackingPaused?'PAUSED':camera.poseFps>0&&camera.poseFps<18?'LOW CAMERA FPS':'TRACKING';$('#preview-box').classList.toggle('hidden',!(camera.running&&(settings.preview||screen==='calibration')));if(camera.running)drawPose();$('#debug-overlay').classList.toggle('hidden',!settings.debug);if(settings.debug){const m=game.motion;$('#debug-overlay').textContent=`${mode.toUpperCase()} / ${m.state}\nRender ${fps.toFixed(0)} fps · camera ${camera.cameraFps.toFixed(0)} fps\nPose ${camera.poseFps.toFixed(0)} fps · inference ${camera.inferenceMs.toFixed(1)} ms\nCapture → result ${camera.latency.toFixed(1)} ms\nConfidence ${m.confidence.toFixed(2)} · hand ${interpreter.calibration.hand}\nSpeed ${m.speed.toFixed(2)} widths/s · power ${m.power.toFixed(2)}\nElbow ${m.elbowAngle.toFixed(0)}° · ${m.plane} · ${m.intent}\nSwing #${m.swingId} / ${m.phase} · used #${game.usedSwing}\nRacket ${game.racket.x.toFixed(2)}, ${game.racket.y.toFixed(2)}, ${game.racket.z.toFixed(2)}\nAI ${game.ai.state} · contacts ${game.totalHits}`;}}
  if(now>toastUntil)$('#toast').classList.add('hidden');
}
requestAnimationFrame(frame);
// Read-only diagnostics for browser acceptance tests and local tuning.
Object.defineProperty(window,'motionDiagnostics',{get:()=>({screen,mode,state:game.state,score:[...game.match.score],fps,cameraFps:camera.cameraFps,poseFps:camera.poseFps,inferenceMs:camera.inferenceMs,latency:camera.latency,workerReady:camera.ready,cameraRunning:camera.running,trackingPaused,contacts:game.totalHits,swingState:game.motion.state,swingId:game.motion.swingId,shuttle:{...game.shuttle.p}})});
